baseURL = "/"
languageCode = "en-us"
title = "RIP Los Angeles"
theme = "Vitae"
paginate = 10

copyright = "© Copyright Nathan Marsak 2022"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

cloudinary_url = "https://res.cloudinary.com/on-bunker-hill/image/upload"


googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"




[params]
	subtitle = "Blogging Los Angeles One Demolition Permit At A Time"

	# Optional 64x64 avatar image.
	avatar = "/images/RIP-LOGO-resizeimage.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3


[[menu.main]]
name = "Nathan's Other Blogs"
url = "https://bunkerhilllosangeles.com"
weight = 4

[[menu.main]]
name = "Esotouric"
url = "https://esotouric.com"
weight = 6

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[permalinks]
posts = "/:slug/"
